name: pactus_gui_widgetbook
description: "This is widget package for using in the pactus GUI project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.16.0+23

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.9.2
  cupertino_icons: ^1.0.8
  mocktail: ^1.0.4
  widgetbook: ^3.14.1
  widgetbook_annotation: ^3.5.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  analyzer: ^7.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.4
  flutter_gen_runner:
  widgetbook_generator: ^3.9.0

flutter_gen:
  output: lib/src/core/utils/gen/assets # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
